stages:
    - test

test:cargo:
    image: "rustlang/rust:nightly"
    stage: test
    script:
        - rustc --version && cargo --version
        - cargo check
        - cargo check --features encoding
        - cargo test
