stages:
    - test

test:cargo:
    image: "rust:latest"
    stage: test
    script:
        - rustc --version && cargo --version
        - cargo check
        - cargo check --features websocket
        - cargo check --features encoding
        - cargo check --features rt
        - cargo test --features encoding,rt,websocket
