stages:
    - test

test:cargo:
    image: "rust:latest"
    stage: test
    script:
        - rustc --version && cargo --version
        - cargo check
        - cargo check --features websocket
        - cargo check --features encoding
        - cargo check --features rt-tokio
        - cargo check --features rt-client
        - cargo check --features rt,rt-tokio-multi
        - cargo test test_global_client --features rt,rt-tokio-multi
        - cargo test --features encoding,rt,websocket
