stages:
    - test

test:cargo:
    image: "rustlang/rust:beta"
    stage: test
    script:
        - rustc --version && cargo --version
        - cargo check --no-default-features
        - cargo check
        - cargo check --features encoding,websocket,docs
        - cargo test
        - cargo test websocket --features websocket
