[package]
name = "yukikaze"
version = "1.0.0"
authors = ["Douman <douman@gmx.se>"]
description = "Beautiful and elegant HTTP library."
readme = "README.md"
repository = "https://gitlab.com/Douman/yukikaze"
license = "Apache-2.0"
keywords = ["http", "http-client"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "README.md"
]
categories = ["web-programming::http-client"]
edition = "2018"

[dependencies.hyper]
version = "0.12"
default-features = false
optional = true

[dependencies]
http = "0.1"
percent-encoding = "1.0"
bytes = "0.4"
mime = "0.3"
mime_guess = "^2.0.0-alpha.6"
flate2 = { version = "1", optional = true }

hyper-rustls = { version = "0.16", optional = true }

httpdate = { version = "0.3", optional = true }
etag = { version = "1", optional = true }
cookie = { version = "0.12", optional = true }
serde = { version = "1", optional = true }
serde_json = { version = "1", optional = true }
serde_urlencoded = { version = "0.5", optional = true }

encoding_rs = { version = "0.8", optional = true }
data-encoding = { version = "2", optional = true }

futures-util-preview = { version = "0.3.0-alpha.15", features = ["compat"] }

derive_more = "0.14"
async-timer = "0.2"

[package.metadata.docs.rs]
features = ["client"]

[features]
default = ["client", "rustls"]
# Enables client
client = ["hyper", "serde", "serde_json", "serde_urlencoded", "data-encoding", "cookie", "etag", "httpdate"]
# Enables usage of rustls, which replaces default connectors
rustls = ["hyper-rustls"]
# Enables encoding/decoding of text content
encoding = ["encoding_rs"]

[dev-dependencies]
tokio = { version = "0.1", default-features = false, features = ["rt-full"] }
