[package]
name = "yukikaze"
version = "0.7.0"
authors = ["Douman <douman@gmx.se>"]
description = "Beautiful and elegant HTTP client library."
readme = "README.md"
repository = "https://gitlab.com/Douman/yukikaze"
license = "Apache-2.0"
keywords = ["http", "http-client"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "README.md"
]
categories = ["web-programming::http-client"]
edition = "2018"

[dependencies.ring]
version = "0.14"
default-features = false

[dependencies.hyper]
version = "0.12"
default-features = false

[dependencies]
hyper-rustls = "0.16"
tokio-timer = "0.2"
bytes = "0.4"
futures = "0.1"
httpdate = "^0.3.2"

http = "0.1"
cookie2 = "0.12"
percent-encoding = "1"
etag = "1"
mime = "0.3"
mime_guess = "^2.0.0-alpha.6"

encoding_rs = { version = "0.8", optional = true }
data-encoding = "2"

serde = "1"
serde_json = "1"
serde_urlencoded = "0.5"

rand = { version = "0.6", optional = true }
flate2 = { version = "^1.0.2", optional = true, default-features = false }
tokio = { version = "0.1", optional = true, default-features = false, features = ["rt-full"] }

derive_more = "0.14"

[package.metadata.docs.rs]
features = ["flate2-c", "encoding", "rt", "webscoket"]

[features]
default = ["flate2-c"]

# Stores request's Extensions in response's Extensions
carry_extensions = []

# Enables Websocket extension
websocket = ["rand", "carry_extensions"]

# Enables encoding/decoding of text content
encoding = ["encoding_rs"]

# Enables tokio runtime module
rt-tokio = ["tokio"]

# Enable multi-threaded tokio runtime
# Overrides rt-tokio
rt-tokio-multi = ["tokio"]

# Enables client runtime module
rt-client = []

# Enables runtime
rt = ["rt-tokio", "rt-client"]

# miniz-sys backend for flate2 crate
flate2-c = ["flate2/miniz-sys"]

# rust backend for flate2 crate
flate2-rust = ["flate2/rust_backend"]

[dev-dependencies]
serde_derive = "1"
tokio = { version = "0.1", default-features = false, features = ["rt-full"] }
