[package]
name = "yukikaze"
version = "1.0.0-alpha.3"
authors = ["Douman <douman@gmx.se>"]
description = "Beautiful and elegant HTTP library."
readme = "README.md"
repository = "https://gitlab.com/Douman/yukikaze"
license = "Apache-2.0"
keywords = ["http", "http-client"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "README.md"
]
categories = ["web-programming::http-client"]
edition = "2018"

[dependencies.hyper]
version = "0.12"
default-features = false
optional = true

[dependencies.ring]
version = "0.14"
default-features = false
optional = true

[dependencies]
http = "0.1"
percent-encoding = "1.0"
bytes = "0.4"
mime = "0.3"
mime_guess = "^2.0.0-alpha.6"
compu = { version = "0.3", optional = true }
lazy_static = "1"

hyper-rustls = { version = "0.16", optional = true }

serde = "1"
serde_json = "1"
cookie = "0.12"
httpdate = { version = "0.3", optional = true }
etag = { version = "1", optional = true }
serde_urlencoded = { version = "0.5", optional = true }

encoding_rs = { version = "0.8", optional = true }
data-encoding = { version = "2", optional = true }
rand = { version = "0.6", optional = true }

futures-util-preview = { version = "0.3.0-alpha.15", features = ["compat"] }

derive_more = "0.14"
async-timer = "0.2"

[package.metadata.docs.rs]
features = ["client", "encoding", "websocket", "docs"]

[features]
default = ["client", "rustls", "compu"]
# Enables client
client = ["hyper", "serde_urlencoded", "data-encoding", "etag", "httpdate"]
# Enables usage of rustls, which replaces default connectors
rustls = ["hyper-rustls"]
# Enables encoding/decoding of text content
encoding = ["encoding_rs"]
# Enables websocket upgrade
websocket = ["ring", "rand", "carry_extensions", "hyper", "data-encoding"]
# Specifies that documentation is being generated
docs = []

# Stores request's Extensions in response's Extensions
carry_extensions = []

[dev-dependencies]
tokio = { version = "0.1", default-features = false, features = ["rt-full"] }
