[package]
name = "yukikaze"
version = "1.0.0-alpha.4"
authors = ["Douman <douman@gmx.se>"]
description = "Beautiful and elegant HTTP library."
readme = "README.md"
repository = "https://gitlab.com/Douman/yukikaze"
license = "Apache-2.0"
keywords = ["http", "http-client"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "README.md"
]
categories = ["web-programming::http-client"]
edition = "2018"

[dependencies.hyper]
git = "https://github.com/hadashiA/hyper.git"
optional = true
default-features = false

[dependencies]
http = "0.1"
percent-encoding = "2.1"
bytes = "0.4"
mime = "0.3"
mime_guess = "2"
compu = { version = "0.4", optional = true, default-features = false, features = ["brotli-c", "zlib-opt"] }
lazy_static = "1"

tokio-tcp = "0.2.0-alpha"

sha-1 = { version = "0", optional = true }
tokio-rustls = { version = "0.12.0-alpha", optional = true }
tokio-io = { version = "0.2.0-alpha", default-features = false, optional = true }
tokio-executor = { version = "0.2.0-alpha", default-features = false, optional = true }
webpki-roots = { version = "0.17", optional = true }

serde = "1"
serde_json = "1"
cookie = "0.12"
httpdate = { version = "0.3", optional = true }
etag = { version = "1", optional = true }
serde_urlencoded = { version = "0.6", optional = true }

encoding_rs = { version = "0.8", optional = true }
data-encoding = { version = "2", optional = true }
getrandom = { version = "0", optional = true }

derive_more = "0.15"
async-timer = { version = "0.4", features = ["tokio_on"] }

futures-util-preview = "0.3.0-alpha"

[package.metadata.docs.rs]
features = ["client", "encoding", "websocket", "docs"]

[features]
default = ["client", "rustls-on", "compu"]
# Enables usage of rustls, which replaces default connectors
rustls-on = ["tokio-rustls", "webpki-roots", "tokio-io"]
# Enables client
client = ["hyper", "serde_urlencoded", "data-encoding", "etag", "httpdate", "tokio-executor"]
# Enables encoding/decoding of text content
encoding = ["encoding_rs"]
# Enables websocket upgrade
websocket = ["sha-1", "getrandom", "carry_extensions", "hyper", "data-encoding"]
# Specifies that documentation is being generated
docs = []

# Stores request's Extensions in response's Extensions
carry_extensions = []

[dev-dependencies]
tokio = { version = "0.2.0-alpha", default-features = false, features = ["rt-full"] }
